services:
    # Form types
    Vrpayment\ContaoIntranetBundle\Form\RequestTokenType:
        class: Vrpayment\ContaoIntranetBundle\Form\RequestTokenType
        arguments:
            - "@contao.csrf.token_manager"
            - "%contao.csrf_token_name%"
        tags:
            - { name: 'form.type' }
